version: '3'

services:
  # Backend API
  # api:
  #   extends:
  #     file: docker-compose.base.yml
  #     service: nx-app-base
  #   command: nx serve api
  #   ports:
  #     - 3000:3000

  # React App
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: api
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

volumes:
  mono-node-modules: null
  postgres_data: null
